import axios from 'axios';
import type { DebtIssue, ScanResult, FixResult, RoadmapData } from '../types';

const apiClient = axios.create({
  baseURL: import.meta.env.VITE_API_URL || '/api',
  headers: {
    'Content-Type': 'application/json',
  },
});

export const api = {
  scanRepo: async (repoUrl: string): Promise<ScanResult> => {
    // Parse GitHub URL to extract owner and repo
    const match = repoUrl.match(/github\.com\/([^\/]+)\/([^\/]+)/);
    if (!match) {
      throw new Error('Invalid GitHub URL');
    }
    
    const [, owner, repo] = match;
    const cleanRepo = repo.replace(/\.git$/, '');
    
    const response = await apiClient.post<any>('/scan', {
      owner,
      repo: cleanRepo,
      branch: 'main',
      options: {
        maxFiles: 1000,
        includeTests: true,
        deepAnalysis: true,
      },
    });
    
    // Transform backend response to match frontend types
    const data = response.data;
    const issues: DebtIssue[] = (data.analysis?.issues || []).map((issue: any, index: number) => ({
      id: issue.id || `DDG-${String(index + 1).padStart(3, '0')}`,
      category: issue.category,
      severity: issue.severity,
      file_path: issue.file || issue.file_path || 'unknown',
      line_range: issue.lines || '1',
      snippet: issue.snippet || '',
      title: issue.problem || issue.title || 'Technical debt issue',
      description: issue.impact || issue.description || 'Needs attention',
      estimated_fix_hours: issue.estimated_fix_hours || 2,
      blast_radius_files: issue.blast_radius || 1,
      dcs_score: issue.business_impact_score || (issue.estimated_fix_hours * 1.5 + (issue.blast_radius || 1) * 0.8 + (issue.severity === 'critical' ? 40 : issue.severity === 'high' ? 30 : issue.severity === 'medium' ? 20 : 10)),
      fix_priority: issue.business_impact_score >= 40 ? 'Fix this week' : issue.business_impact_score >= 25 ? 'Fix this sprint' : issue.business_impact_score >= 15 ? 'Fix this quarter' : 'Monitor',
      sprint_velocity_drag: `${(issue.estimated_fix_hours * 0.5).toFixed(1)} hours/sprint lost`,
      roi_if_fixed_now: `saves $${(issue.estimated_fix_hours * 50 * 26).toLocaleString()} over 6 months`,
      auto_fixable: issue.auto_fixable || false,
    }));

    
    const summary = data.analysis?.summary || {};
    
    return {
      repo_url: repoUrl,
      scanned_at: new Date().toISOString(),
      issues,
      total_debt_hours: summary.total_estimated_hours || issues.reduce((sum, i) => sum + i.estimated_fix_hours, 0),
      monthly_cost_estimate: (summary.total_estimated_hours || 0) * 50 * 4,
      summary: {
        critical: issues.filter(i => i.severity === 'critical').length,
        high: issues.filter(i => i.severity === 'high').length,
        medium: issues.filter(i => i.severity === 'medium').length,
        low: issues.filter(i => i.severity === 'low').length,
        auto_fixable: summary.auto_fixable_count || issues.filter(i => i.auto_fixable).length,
        total_issues: summary.total_issues || issues.length,
        most_common_issue: summary.most_common_issue,
        highest_risk_area: summary.highest_risk_area,
      },
      repository: data.repository,
      metadata: data.metadata,
      analysis: data.analysis,
      roadmap: data.roadmap,
      cost_savings: data.cost_savings,
      files: data.files,
    };

  },

  generateFix: async (issueId: string, issue: DebtIssue, repoUrl: string): Promise<FixResult> => {
    const match = repoUrl.match(/github\.com\/([^\/]+)\/([^\/]+)/);
    if (!match) {
      throw new Error('Invalid GitHub URL');
    }
    
    const [, owner, repo] = match;
    const cleanRepo = repo.replace(/\.git$/, '');
    
    const response = await apiClient.post<any>(`/fix/${issueId}`, {
      owner,
      repo: cleanRepo,
      issue: {
        id: issue.id,
        category: issue.category,
        file: issue.file_path,
        problem: issue.title,
        impact: issue.description,
        estimated_fix_hours: issue.estimated_fix_hours,
        severity: issue.severity,
        auto_fixable: issue.auto_fixable,
      },
      fileContent: issue.snippet || '// File content placeholder',
    });
    
    const plan = response.data.plan || {};
    
    return {
      issue_id: issueId,
      explanation: plan.fix_description || 'Fix generated by IBM Bob',
      fixed_code: plan.code_changes?.[0]?.content || '// Fixed code will appear here',
      test_code: plan.test_changes?.[0]?.content || '// Test code will appear here',
      pr_title: plan.pr_title || `fix: ${issue.title}`,
      pr_body: plan.pr_description || '## Summary\nFix generated by DevDriftGuard',
      dependent_changes: [],
      test_count: plan.test_changes?.length || 3,
      plan,
    };
  },

  createPR: async (owner: string, repo: string, plan: any): Promise<{ pr_number: number; pr_url: string }> => {
    const response = await apiClient.post<any>('/pr/create', {
      owner,
      repo,
      plan,
    });
    return response.data;
  },


  chat: async (message: string, context: { repo?: string; issues?: DebtIssue[]; selectedIssue?: DebtIssue }): Promise<string> => {
    try {
      const response = await apiClient.post<any>('/chat', {
        message,
        context: {
          repo: context.repo,
          selectedIssue: context.selectedIssue ? {
            title: context.selectedIssue.title,
            category: context.selectedIssue.category,
            severity: context.selectedIssue.severity,
            file_path: context.selectedIssue.file_path,
            description: context.selectedIssue.description,
          } : null
        },
      });
      return response.data.reply;
    } catch (error) {
      console.error('Chat API error:', error);
      return "I'm having trouble connecting to my brain right now. Please try again in a moment.";
    }
  },

  generateRoadmap: async (issues: DebtIssue[]): Promise<RoadmapData> => {
    // Sort issues by DCS score
    const sortedIssues = [...issues].sort((a, b) => b.dcs_score - a.dcs_score);
    
    const week1 = sortedIssues.slice(0, 3).map(i => `${i.id}: ${i.title} (${i.estimated_fix_hours}h)`);
    const week2 = sortedIssues.slice(3, 6).map(i => `${i.id}: ${i.title} (${i.estimated_fix_hours}h)`);
    const week3 = sortedIssues.slice(6, 9).map(i => `${i.id}: ${i.title} (${i.estimated_fix_hours}h)`);
    
    const total_hours = sortedIssues.slice(0, 9).reduce((sum, i) => sum + i.estimated_fix_hours, 0);
    const monthly_savings = Math.round(total_hours * 50 * 4);
    
    return {
      week1,
      week2,
      week3,
      total_hours,
      monthly_savings,
    };
  },

  exportReport: (result: ScanResult): string => {
    // Generate advanced HTML report for PDF printing
    const repoName = result.repo_url.split('/').slice(-2).join('/');
    const criticalHighCount = result.summary.critical + result.summary.high;
    
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>DevDriftGuard Report - ${repoName}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap');
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    
    body {
      font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      color: #161616;
      background: #ffffff;
    }
    
    .page {
      max-width: 1200px;
      margin: 0 auto;
      padding: 60px 80px;
      background: white;
    }
    
    /* Cover Page */
    .cover-page {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      text-align: center;
      background: linear-gradient(135deg, #0f62fe 0%, #001d6c 100%);
      color: white;
      page-break-after: always;
      padding: 80px;
    }
    
    .cover-logo {
      width: 120px;
      height: 120px;
      background: white;
      border-radius: 24px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 48px;
      font-weight: 700;
      color: #0f62fe;
      margin-bottom: 40px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
    }
    
    .cover-title {
      font-size: 56px;
      font-weight: 700;
      margin-bottom: 20px;
      letter-spacing: -1px;
    }
    
    .cover-subtitle {
      font-size: 28px;
      font-weight: 400;
      opacity: 0.9;
      margin-bottom: 60px;
    }
    
    .cover-repo {
      font-family: 'IBM Plex Mono', monospace;
      font-size: 20px;
      background: rgba(255,255,255,0.15);
      padding: 16px 32px;
      border-radius: 8px;
      margin-bottom: 40px;
      backdrop-filter: blur(10px);
    }
    
    .cover-meta {
      font-size: 16px;
      opacity: 0.8;
      margin-top: 60px;
    }
    
    .cover-stats {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 40px;
      margin-top: 80px;
      width: 100%;
      max-width: 900px;
    }
    
    .cover-stat {
      background: rgba(255,255,255,0.1);
      padding: 30px;
      border-radius: 12px;
      backdrop-filter: blur(10px);
      border: 1px solid rgba(255,255,255,0.2);
    }
    
    .cover-stat-value {
      font-size: 48px;
      font-weight: 700;
      margin-bottom: 8px;
    }
    
    .cover-stat-label {
      font-size: 14px;
      text-transform: uppercase;
      letter-spacing: 1px;
      opacity: 0.8;
    }
    
    /* Content Pages */
    .content-page {
      page-break-before: always;
      padding: 60px 0;
    }
    
    .page-header {
      margin-bottom: 50px;
      padding-bottom: 20px;
      border-bottom: 3px solid #0f62fe;
    }
    
    .page-title {
      font-size: 36px;
      font-weight: 700;
      color: #0f62fe;
      margin-bottom: 8px;
    }
    
    .page-description {
      font-size: 16px;
      color: #525252;
    }
    
    /* Executive Summary */
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 24px;
      margin-bottom: 40px;
    }
    
    .metric-card {
      background: linear-gradient(135deg, #f4f4f4 0%, #e8e8e8 100%);
      padding: 32px;
      border-radius: 12px;
      border-left: 6px solid #0f62fe;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    }
    
    .metric-label {
      font-size: 13px;
      color: #525252;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 12px;
      font-weight: 600;
    }
    
    .metric-value {
      font-size: 48px;
      font-weight: 700;
      color: #0f62fe;
      line-height: 1;
    }
    
    .metric-subtext {
      font-size: 14px;
      color: #8d8d8d;
      margin-top: 8px;
    }
    
    /* Severity Breakdown */
    .severity-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 20px;
      margin-bottom: 40px;
    }
    
    .severity-card {
      background: white;
      padding: 28px;
      border-radius: 12px;
      text-align: center;
      border: 2px solid #e0e0e0;
      transition: transform 0.2s;
    }
    
    .severity-card.critical { border-color: #da1e28; background: #fff1f1; }
    .severity-card.high { border-color: #f1c21b; background: #fcf4d6; }
    .severity-card.medium { border-color: #0f62fe; background: #e8f4ff; }
    .severity-card.low { border-color: #8d8d8d; background: #f4f4f4; }
    
    .severity-count {
      font-size: 56px;
      font-weight: 700;
      line-height: 1;
      margin-bottom: 12px;
    }
    
    .severity-card.critical .severity-count { color: #da1e28; }
    .severity-card.high .severity-count { color: #f1c21b; }
    .severity-card.medium .severity-count { color: #0f62fe; }
    .severity-card.low .severity-count { color: #8d8d8d; }
    
    .severity-label {
      font-size: 13px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      font-weight: 600;
      color: #525252;
    }
    
    /* Issue Cards */
    .issue-card {
      background: white;
      border: 2px solid #e0e0e0;
      border-radius: 12px;
      padding: 28px;
      margin-bottom: 20px;
      page-break-inside: avoid;
      box-shadow: 0 2px 8px rgba(0,0,0,0.06);
    }
    
    .issue-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 16px;
      gap: 20px;
    }
    
    .issue-title {
      font-size: 18px;
      font-weight: 600;
      color: #161616;
      flex: 1;
      line-height: 1.4;
    }
    
    .issue-badge {
      padding: 6px 16px;
      border-radius: 6px;
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      white-space: nowrap;
    }
    
    .issue-badge.critical { background: #da1e28; color: white; }
    .issue-badge.high { background: #f1c21b; color: #161616; }
    .issue-badge.medium { background: #0f62fe; color: white; }
    .issue-badge.low { background: #8d8d8d; color: white; }
    
    .issue-description {
      font-size: 15px;
      color: #525252;
      line-height: 1.6;
      margin-bottom: 16px;
    }
    
    .issue-file {
      font-family: 'IBM Plex Mono', monospace;
      font-size: 13px;
      color: #0f62fe;
      background: #f4f4f4;
      padding: 12px 16px;
      border-radius: 6px;
      border-left: 3px solid #0f62fe;
      margin-bottom: 16px;
    }
    
    .issue-metrics {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 16px;
      padding-top: 16px;
      border-top: 2px solid #e0e0e0;
    }
    
    .issue-metric {
      text-align: center;
    }
    
    .issue-metric-label {
      font-size: 11px;
      color: #8d8d8d;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 6px;
      font-weight: 600;
    }
    
    .issue-metric-value {
      font-size: 20px;
      font-weight: 700;
      color: #161616;
    }
    
    .dcs-score {
      color: #0f62fe;
      font-size: 24px;
    }
    
    /* Footer */
    .report-footer {
      margin-top: 80px;
      padding-top: 30px;
      border-top: 3px solid #e0e0e0;
      text-align: center;
      color: #8d8d8d;
      font-size: 13px;
    }
    
    .footer-logo {
      font-size: 18px;
      font-weight: 700;
      color: #0f62fe;
      margin-bottom: 8px;
    }
    
    .footer-text {
      margin-bottom: 4px;
    }
    
    /* Print Styles */
    @media print {
      body { background: white; }
      .page { padding: 40px; }
      .issue-card { page-break-inside: avoid; }
      .content-page { page-break-before: always; }
    }
  </style>
</head>
<body>
  <!-- Cover Page -->
  <div class="cover-page">
    <div class="cover-logo">DD</div>
    <h1 class="cover-title">Technical Debt Report</h1>
    <div class="cover-subtitle">AI-Powered Code Quality Analysis</div>
    <div class="cover-repo">${repoName}</div>
    <div class="cover-meta">Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
    
    <div class="cover-stats">
      <div class="cover-stat">
        <div class="cover-stat-value">${result.summary.total_issues}</div>
        <div class="cover-stat-label">Total Issues</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-value">${criticalHighCount}</div>
        <div class="cover-stat-label">Critical/High</div>
      </div>
      <div class="cover-stat">
        <div class="cover-stat-value">${result.total_debt_hours}h</div>
        <div class="cover-stat-label">Debt Hours</div>
      </div>
    </div>
  </div>

  <!-- Executive Summary Page -->
  <div class="page content-page">
    <div class="page-header">
      <h2 class="page-title">Executive Summary</h2>
      <p class="page-description">Key metrics and financial impact analysis</p>
    </div>
    
    <div class="metrics-grid">
      <div class="metric-card">
        <div class="metric-label">Total Issues Detected</div>
        <div class="metric-value">${result.summary.total_issues}</div>
        <div class="metric-subtext">Across ${result.issues.length > 0 ? new Set(result.issues.map(i => i.file_path)).size : 0} files</div>
      </div>
      
      <div class="metric-card">
        <div class="metric-label">Total Technical Debt</div>
        <div class="metric-value">${result.total_debt_hours}h</div>
        <div class="metric-subtext">Estimated remediation time</div>
      </div>
      
      <div class="metric-card">
        <div class="metric-label">Monthly Cost Impact</div>
        <div class="metric-value">$${Math.round(result.monthly_cost_estimate).toLocaleString()}</div>
        <div class="metric-subtext">Based on developer productivity loss</div>
      </div>
      
      <div class="metric-card">
        <div class="metric-label">Auto-Fixable Issues</div>
        <div class="metric-value">${result.summary.auto_fixable}</div>
        <div class="metric-subtext">${Math.round((result.summary.auto_fixable / result.summary.total_issues) * 100)}% can be fixed automatically</div>
      </div>
    </div>
    
    <div class="page-header" style="margin-top: 60px;">
      <h2 class="page-title">Severity Distribution</h2>
      <p class="page-description">Issues categorized by urgency and business impact</p>
    </div>
    
    <div class="severity-grid">
      <div class="severity-card critical">
        <div class="severity-count">${result.summary.critical}</div>
        <div class="severity-label">Critical</div>
      </div>
      <div class="severity-card high">
        <div class="severity-count">${result.summary.high}</div>
        <div class="severity-label">High</div>
      </div>
      <div class="severity-card medium">
        <div class="severity-count">${result.summary.medium}</div>
        <div class="severity-label">Medium</div>
      </div>
      <div class="severity-card low">
        <div class="severity-count">${result.summary.low}</div>
        <div class="severity-label">Low</div>
      </div>
    </div>
  </div>

  <!-- Issues Detail Page -->
  <div class="page content-page">
    <div class="page-header">
      <h2 class="page-title">Detailed Issue Analysis</h2>
      <p class="page-description">Top ${Math.min(20, result.issues.length)} issues ranked by DCS (Debt Cost Score)</p>
    </div>
    
    ${result.issues.slice(0, 20).map((issue, index) => `
      <div class="issue-card">
        <div class="issue-header">
          <div class="issue-title">${index + 1}. ${issue.title}</div>
          <span class="issue-badge ${issue.severity}">${issue.severity}</span>
        </div>
        
        <div class="issue-description">${issue.description}</div>
        
        <div class="issue-file">${issue.file_path} <span style="color: #8d8d8d;">• Lines ${issue.line_range}</span></div>
        
        <div class="issue-metrics">
          <div class="issue-metric">
            <div class="issue-metric-label">DCS Score</div>
            <div class="issue-metric-value dcs-score">${issue.dcs_score.toFixed(1)}</div>
          </div>
          <div class="issue-metric">
            <div class="issue-metric-label">Fix Time</div>
            <div class="issue-metric-value">${issue.estimated_fix_hours}h</div>
          </div>
          <div class="issue-metric">
            <div class="issue-metric-label">Priority</div>
            <div class="issue-metric-value">${issue.fix_priority}</div>
          </div>
          <div class="issue-metric">
            <div class="issue-metric-label">Auto-Fix</div>
            <div class="issue-metric-value">${issue.auto_fixable ? 'Yes' : 'No'}</div>
          </div>
        </div>
      </div>
    `).join('')}
    
    <div class="report-footer">
      <div class="footer-logo">DevDriftGuard v1.0.0</div>
      <div class="footer-text">AI-Powered Technical Debt Management System</div>
      <div class="footer-text">Powered by IBM Bob and NVIDIA AI</div>
      <div class="footer-text" style="margin-top: 12px; color: #c6c6c6;">This report was automatically generated by analyzing ${result.issues.length > 0 ? new Set(result.issues.map(i => i.file_path)).size : 0} source files</div>
    </div>
  </div>
</body>
</html>
    `;
    return html;
  },
};

// Made with Bob
